# Generated by Django 5.2.1 on 2025-05-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_paciente_bairro_alter_paciente_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='cidade',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='estado',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
